### ISSUE TITLE
Button Toggle

### ISSUE THREAD

**Issue by Brody0727** [AWeirDKiD/YT-AntiAdBlock-Bypass#2]
Just an idea/complaint, but the Bypasser Settings button in YouTube is obnoxious due to its location. Could you add a toggle to disable it but not the extension?

**Comment by Yaw-Dev** [comment]
> Just an idea/complaint, but the Bypasser Settings button in YouTube is obnoxious due to its location. Could you add a toggle to disable it but not the extension?

This already exists. Simply press the insert key (ins).
