### ISSUE TITLE
skip the silly page after the ad 

### ISSUE THREAD

**Issue by Half-0001** [AWeirDKiD/YT-AntiAdBlock-Bypass#3]
the adblock has been working fine, but recently after every advert its added another page that you need to click skip ad on at the end, could you make it so the script automatically does this please i am very lazy 
![image](https://github.com/Yaw-Dev/YT-AntiAdBlock-Bypass/assets/108597230/925f2198-ad70-4b5f-80c3-972cc16f8fd1)

**Comment by Yaw-Dev** [comment]
That hasn't really happened to me from what I can remember. I will try doing something about it if it ever pops up. Do not expect any changes soon tho, uBlock Origin works just fine on YouTube so I haven't really been using / developing this the past weeks.
